[tool.briefcase]
project_name = "Hello World"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/helloworld"
license.file = "LICENSE"
author = "Jane Developer"
author_email = "jane@example.com"

[tool.briefcase.app.helloworld]
formal_name = "Hello World"
description = "My first application"
long_description = """More details about the app should go here.
"""
sources = [
    "src/helloworld",
]
test_sources = [
    "tests",
]

requires = [
    "toga~=0.3.0",
    "qrcode[pil]",
    "Pillow",
]
test_requires = [
    "pytest",
]

[tool.briefcase.app.helloworld.macOS]
universal_build = true
requires = [
    "toga-cocoa~=0.3.0",
    "std-nslog~=1.0.0",
]

[tool.briefcase.app.helloworld.linux]
requires = [
    "toga-gtk~=0.3.0",
]

[tool.briefcase.app.helloworld.linux.system.debian]
system_requires = [
    "libcairo2-dev",
    "libgirepository1.0-dev",
]

system_runtime_requires = [
    "gir1.2-gtk-3.0",
    "libgirepository-1.0-1",
    "libcanberra-gtk3-module",
]

[tool.briefcase.app.helloworld.linux.system.rhel]
system_requires = [
    "cairo-gobject-devel",
    "gobject-introspection-devel",
]

system_runtime_requires = [
    "gobject-introspection",
    "gtk3",
    "libcanberra-gtk3",
]

[tool.briefcase.app.helloworld.linux.system.suse]
system_requires = [
    "cairo-devel",
    "gobject-introspection-devel",
]

system_runtime_requires = [
    "gtk3",
    "gobject-introspection", "typelib(Gtk) = 3.0",
    "libcanberra-gtk3-module",
]

[tool.briefcase.app.helloworld.linux.system.arch]
system_requires = [
    "cairo",
    "gobject-introspection",
    "gtk3",
    "libcanberra",
]

system_runtime_requires = [
    "gtk3",
    "gobject-introspection-runtime",
    "libcanberra",
]

[tool.briefcase.app.helloworld.linux.appimage]
manylinux = "manylinux_2_28"

system_requires = [
    "cairo-gobject-devel",
    "gobject-introspection-devel",
    "gtk3-devel",
    "libcanberra-gtk3",
    "PackageKit-gtk3-module",
    "gvfs-client",
]

linuxdeploy_plugins = [
    "DEPLOY_GTK_VERSION=3 gtk",
]

[tool.briefcase.app.helloworld.linux.flatpak]
flatpak_runtime = "org.gnome.Platform"
flatpak_runtime_version = "45"
flatpak_sdk = "org.gnome.Sdk"

[tool.briefcase.app.helloworld.windows]
requires = [
    "toga-winforms~=0.3.0",
]

[tool.briefcase.app.helloworld.iOS]
requires = [
    "toga-iOS~=0.3.0",
    "std-nslog~=1.0.0",
]

[tool.briefcase.app.helloworld.android]
requires = [
    "toga-android~=0.3.0",
]

base_theme = "Theme.MaterialComponents.Light.DarkActionBar"

build_gradle_dependencies = [
    "com.google.android.material:material:1.11.0",
]

[tool.briefcase.app.helloworld.web]
requires = [
    "toga-web~=0.3.0",
]
style_framework = "Shoelace v2.3"
